import clsx from 'clsx'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Grandstander } from 'next/font/google'
import Nav from './components/nav'
import { UserProvider } from '@auth0/nextjs-auth0/client'

const grandstander = Grandstander({ subsets: ['latin'], weight: '600' })
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Total React',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={clsx(' flex flex-col justify-evenly')}>
          <div className={clsx(grandstander.className, 'flex')}>
            <Nav />
          </div>
          <div className={inter.className}>{children}</div>
        </body>
      </UserProvider>
    </html>
  )
}
